name: manage-azure-policy-ac3786cc
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/MFA_should_be_enabled_on_accounts_with_owner_permissions_on_your_subscription_aa633080-8b72-40c4-a2d7-d00c03e80bed/**'
#      - 'policies/MFA_should_be_enabled_accounts_with_write_permissions_on_your_subscription_9297c21d-2ed6-4474-b48f-163f75654ce3/**'
#      - 'policies/External_accounts_with_owner_permissions_should_be_removed_from_your_subscription_f8456c1c-aa66-4dfb-861a-25d127b775c9/**'
#      - 'policies/External_accounts_with_read_permissions_should_be_removed_from_your_subscription_5f76cf89-fbf2-47fd-a3f4-b891fa780b60/**'
#      - 'policies/Deprecated_accounts_should_be_removed_from_your_subscription_6b1cbf55-e8b6-442f-ba4c-7246b6381474/**'
#      - 'policies/Deprecated_accounts_with_owner_permissions_should_be_removed_from_your_subscription_ebb62a0c-3560-49e1-89ed-27e074e9f8ad/**'
#      - 'policies/Add_system-assigned_managed_identity_to_enable_Guest_Configuration_assignments_on_virtual_machines_with_no_identities_3cf2ab00-13f1-4d0c-8971-2ac904541a7e/**'
#      - 'policies/External_accounts_with_write_permissions_should_be_removed_from_your_subscription_5c607a2e-c700-4744-8254-d77e7c9eb5e4/**'
#      - 'policies/Add_system-assigned_managed_identity_to_enable_Guest_Configuration_assignments_on_VMs_with_a_user-assigned_identity_497dff13-db2a-4c0f-8603-28fa3b331ab6/**'
#      - 'policies/Deploy_the_Windows_Guest_Configuration_extension_to_enable_Guest_Configuration_assignments_on_Windows_VMs_385f5831-96d4-41db-9a3c-cd3af78aaae6/**'
#      - 'policies/Audit_Windows_machines_that_do_not_have_a_maximum_password_age_of_70_days_4ceb8dc2-559c-478b-a15b-733fbf1e3738/**'
#      - 'policies/Audit_Windows_machines_that_do_not_restrict_the_minimum_password_length_to_14_characters_a2d0e922-65d0-40c4-8f87-ea6da2d307a2/**'
#      - 'policies/Audit_Windows_machines_that_allow_re-use_of_the_previous_24_passwords_5b054a0d-39e2-4d53-bea3-9734cad2c69b/**'
#      - .github/workflows/manage-azure-policy-ac3786cc.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ac3786cc}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/MFA_should_be_enabled_on_accounts_with_owner_permissions_on_your_subscription_aa633080-8b72-40c4-a2d7-d00c03e80bed/**
          policies/MFA_should_be_enabled_accounts_with_write_permissions_on_your_subscription_9297c21d-2ed6-4474-b48f-163f75654ce3/**
          policies/External_accounts_with_owner_permissions_should_be_removed_from_your_subscription_f8456c1c-aa66-4dfb-861a-25d127b775c9/**
          policies/External_accounts_with_read_permissions_should_be_removed_from_your_subscription_5f76cf89-fbf2-47fd-a3f4-b891fa780b60/**
          policies/Deprecated_accounts_should_be_removed_from_your_subscription_6b1cbf55-e8b6-442f-ba4c-7246b6381474/**
          policies/Deprecated_accounts_with_owner_permissions_should_be_removed_from_your_subscription_ebb62a0c-3560-49e1-89ed-27e074e9f8ad/**
          policies/Add_system-assigned_managed_identity_to_enable_Guest_Configuration_assignments_on_virtual_machines_with_no_identities_3cf2ab00-13f1-4d0c-8971-2ac904541a7e/**
          policies/External_accounts_with_write_permissions_should_be_removed_from_your_subscription_5c607a2e-c700-4744-8254-d77e7c9eb5e4/**
          policies/Add_system-assigned_managed_identity_to_enable_Guest_Configuration_assignments_on_VMs_with_a_user-assigned_identity_497dff13-db2a-4c0f-8603-28fa3b331ab6/**
          policies/Deploy_the_Windows_Guest_Configuration_extension_to_enable_Guest_Configuration_assignments_on_Windows_VMs_385f5831-96d4-41db-9a3c-cd3af78aaae6/**
          policies/Audit_Windows_machines_that_do_not_have_a_maximum_password_age_of_70_days_4ceb8dc2-559c-478b-a15b-733fbf1e3738/**
          policies/Audit_Windows_machines_that_do_not_restrict_the_minimum_password_length_to_14_characters_a2d0e922-65d0-40c4-8f87-ea6da2d307a2/**
          policies/Audit_Windows_machines_that_allow_re-use_of_the_previous_24_passwords_5b054a0d-39e2-4d53-bea3-9734cad2c69b/**
